# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListArtists = QtWidgets.QListWidget(self.centralwidget)
        self.ListArtists.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ListArtists.setObjectName("ListArtists")
        self.horizontalLayout.addWidget(self.ListArtists, 0, QtCore.Qt.AlignLeft)
        self.ListTracks = QtWidgets.QListWidget(self.centralwidget)
        self.ListTracks.setObjectName("ListTracks")
        self.horizontalLayout.addWidget(self.ListTracks)
        self.Playlist = QtWidgets.QListWidget(self.centralwidget)
        self.Playlist.setObjectName("Playlist")
        self.horizontalLayout.addWidget(self.Playlist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(10, 10, -1, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 80))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Next = QtWidgets.QPushButton(self.groupBox)
        self.Next.setMinimumSize(QtCore.QSize(26, 26))
        self.Next.setMaximumSize(QtCore.QSize(26, 26))
        self.Next.setObjectName("Next")
        self.horizontalLayout_3.addWidget(self.Next)
        self.PlayPause = QtWidgets.QPushButton(self.groupBox)
        self.PlayPause.setMinimumSize(QtCore.QSize(26, 26))
        self.PlayPause.setMaximumSize(QtCore.QSize(26, 26))
        self.PlayPause.setObjectName("PlayPause")
        self.horizontalLayout_3.addWidget(self.PlayPause)
        self.Stop = QtWidgets.QPushButton(self.groupBox)
        self.Stop.setMinimumSize(QtCore.QSize(26, 26))
        self.Stop.setMaximumSize(QtCore.QSize(26, 26))
        self.Stop.setObjectName("Stop")
        self.horizontalLayout_3.addWidget(self.Stop)
        self.Previous = QtWidgets.QPushButton(self.groupBox)
        self.Previous.setMinimumSize(QtCore.QSize(26, 26))
        self.Previous.setMaximumSize(QtCore.QSize(26, 26))
        self.Previous.setObjectName("Previous")
        self.horizontalLayout_3.addWidget(self.Previous)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Position = QtWidgets.QSlider(self.centralwidget)
        self.Position.setOrientation(QtCore.Qt.Horizontal)
        self.Position.setObjectName("Position")
        self.verticalLayout.addWidget(self.Position)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRightClick = QtWidgets.QAction(MainWindow)
        self.actionRightClick.setObjectName("actionRightClick")
        self.actionLeftClick = QtWidgets.QAction(MainWindow)
        self.actionLeftClick.setObjectName("actionLeftClick")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Controls"))
        self.Next.setText(_translate("MainWindow", "Next"))
        self.PlayPause.setText(_translate("MainWindow", "Play"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Previous.setText(_translate("MainWindow", "Prev"))
        self.actionRightClick.setText(_translate("MainWindow", "RightClick"))
        self.actionLeftClick.setText(_translate("MainWindow", "LeftClick"))

